matrix:
  include:
    - language: php
      sudo: false
      php: 7.4
      cache:
        directories:
          - $HOME/.composer/cache/files
      before_script:
        - composer install --ignore-platform-reqs
      script:
        - composer run-script travis
      after_success:
        - travis_retry php vendor/bin/php-coveralls
